// ─── Types ───────────────────────────────────────────────────────

export type Language = 'ja' | 'vi' | 'id' | 'en' | 'my' | 'zh';
export type Industry =
  | 'all'
  | 'manufacturing'
  | 'care'
  | 'food'
  | 'retail'
  | 'logistics'
  | 'construction';

export type ParamDef = {
  key: string;
  default: number;
  min: number;
  max: number;
  unit: string;
};

export type RuleItem = {
  id: string;
  icon?: string;
  industries: Industry[];
  ja: string;
  vi: string;
  id_lang: string;
  en: string;
  my: string;
  zh: string;
  params?: ParamDef[];
  usesSupervisorName?: boolean;
  jaRuby?: string;
  context?: Record<Language, string>;
};

// ─── Constants ───────────────────────────────────────────────────

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'ja', label: '日本語', flag: '\u{1F1EF}\u{1F1F5}' },
  { code: 'vi', label: 'ベトナム語', flag: '\u{1F1FB}\u{1F1F3}' },
  { code: 'id', label: 'インドネシア語', flag: '\u{1F1EE}\u{1F1E9}' },
  { code: 'en', label: '英語', flag: '\u{1F1EC}\u{1F1E7}' },
  { code: 'my', label: 'ミャンマー語', flag: '\u{1F1F2}\u{1F1F2}' },
  { code: 'zh', label: '中国語', flag: '\u{1F1E8}\u{1F1F3}' },
];

export const INDUSTRIES: { code: Industry; label: string }[] = [
  { code: 'all', label: 'すべて' },
  { code: 'manufacturing', label: '製造業' },
  { code: 'care', label: '介護' },
  { code: 'food', label: '食品' },
  { code: 'retail', label: '小売・接客' },
  { code: 'logistics', label: '物流' },
  { code: 'construction', label: '建設' },
];

// ─── UI Labels (5 languages, used in print output) ───────────────

export const UI: Record<
  Language,
  {
    title: string;
    subtitle: string;
    safety: string;
    emergency: string;
    daily: string;
    phrases: string;
    companySection: string;
    labelCompany: string;
    labelSupervisor: string;
    labelSupervisorKana: string;
    labelPhone: string;
    labelEmergency: string;
    footer: string;
  }
> = {
  ja: {
    title: '現場の大切なルール',
    subtitle: '',
    safety: '🦺 安全ルール',
    emergency: '🚨 緊急のとき',
    daily: '📋 毎日のルール',
    phrases: '💬 よく使う言葉',
    companySection: '✏️ 記入欄',
    labelCompany: '会社名',
    labelSupervisor: '担当者',
    labelSupervisorKana: 'ふりがな',
    labelPhone: '電話番号',
    labelEmergency: '緊急連絡先',
    footer: 'このシートは会社からの支給品です',
  },
  vi: {
    title: 'Nội Quy Quan Trọng Tại Nơi Làm Việc',
    subtitle: '現場の大切なルール',
    safety: '🦺 Quy tắc an toàn',
    emergency: '🚨 Khi khẩn cấp',
    daily: '📋 Quy định hàng ngày',
    phrases: '💬 Những câu thường dùng',
    companySection: '✏️ Thông tin công ty',
    labelCompany: 'Tên công ty（会社名）',
    labelSupervisor: 'Người phụ trách（担当者）',
    labelSupervisorKana: 'Cách đọc（ふりがな）',
    labelPhone: 'Số điện thoại（電話番号）',
    labelEmergency: 'Liên hệ khẩn cấp（緊急連絡先）',
    footer: 'Tài liệu này được cung cấp bởi công ty của bạn',
  },
  id: {
    title: 'Peraturan Penting di Tempat Kerja',
    subtitle: '現場の大切なルール',
    safety: '🦺 Aturan Keselamatan',
    emergency: '🚨 Saat Darurat',
    daily: '📋 Aturan Sehari-hari',
    phrases: '💬 Kalimat yang Sering Digunakan',
    companySection: '✏️ Informasi Perusahaan',
    labelCompany: 'Nama perusahaan（会社名）',
    labelSupervisor: 'Penanggung jawab（担当者）',
    labelSupervisorKana: 'Cara baca（ふりがな）',
    labelPhone: 'Nomor telepon（電話番号）',
    labelEmergency: 'Kontak darurat（緊急連絡先）',
    footer: 'Lembar ini diberikan oleh perusahaan Anda',
  },
  en: {
    title: 'Important Workplace Rules',
    subtitle: '現場の大切なルール',
    safety: '🦺 Safety Rules',
    emergency: '🚨 In Case of Emergency',
    daily: '📋 Daily Rules',
    phrases: '💬 Useful Phrases',
    companySection: '✏️ Company Information',
    labelCompany: 'Company name（会社名）',
    labelSupervisor: 'Supervisor（担当者）',
    labelSupervisorKana: 'Name reading（ふりがな）',
    labelPhone: 'Phone number（電話番号）',
    labelEmergency: 'Emergency contact（緊急連絡先）',
    footer: 'This sheet is provided by your company',
  },
  my: {
    title: 'အလုပ်ခွင် အရေးကြီး စည်းကမ်းများ',
    subtitle: '現場の大切なルール',
    safety: '🦺 လုံခြုံရေးစည်းကမ်းများ',
    emergency: '🚨 အရေးပေါ်အခြေအနေ',
    daily: '📋 နေ့စဉ်စည်းကမ်းများ',
    phrases: '💬 အသုံးများသောစကားများ',
    companySection: '✏️ ကုမ္ပဏီအချက်အလက်',
    labelCompany: 'ကုမ္ပဏီနာမည်（会社名）',
    labelSupervisor: 'တာဝန်ခံ（担当者）',
    labelSupervisorKana: 'အမည်ဖတ်ပုံ（ふりがな）',
    labelPhone: 'ဖုန်းနံပါတ်（電話番号）',
    labelEmergency: 'အရေးပေါ်ဆက်သွယ်ရန်（緊急連絡先）',
    footer: 'ဤစာရွက်ကို သင့်ကုမ္ပဏီမှ ပေးအပ်ပါသည်',
  },
  zh: {
    title: '工作场所重要规则',
    subtitle: '現場の大切なルール',
    safety: '🦺 安全规则',
    emergency: '🚨 紧急情况',
    daily: '📋 日常规则',
    phrases: '💬 常用语句',
    companySection: '✏️ 填写栏',
    labelCompany: '公司名称（会社名）',
    labelSupervisor: '负责人（担当者）',
    labelSupervisorKana: '假名拼音（ふりがな）',
    labelPhone: '电话号码（電話番号）',
    labelEmergency: '紧急联系方式（緊急連絡先）',
    footer: '本材料由贵公司提供',
  },
};

// ─── Safety Rules (S01–S16) ──────────────────────────────────────

export const SAFETY_RULES: RuleItem[] = [
  {
    id: 'S01',
    icon: '⚙️',
    industries: ['manufacturing', 'construction'],
    ja: '機械を使う前に、必ず確認してください',
    vi: 'Trước khi sử dụng máy móc, hãy kiểm tra cẩn thận',
    id_lang: 'Sebelum menggunakan mesin, periksa terlebih dahulu',
    en: 'Always check before using any machinery',
    my: 'စက်ပစ္စည်းသုံးမည်ဆိုရင် အသုံးမပြုမီ သေချာစစ်ဆေးပါ',
    zh: '使用机器前，请务必确认安全',
  },
  {
    id: 'S02',
    icon: '🚫',
    industries: ['manufacturing', 'logistics', 'construction'],
    ja: '赤いエリアには入ってはいけません',
    vi: 'Không được vào khu vực màu đỏ',
    id_lang: 'Dilarang masuk ke area merah',
    en: 'Do not enter red zones',
    my: 'နီသောနေရာသို့ မဝင်ပါနှင့်',
    zh: '禁止进入红色区域',
  },
  {
    id: 'S03',
    icon: '🩹',
    industries: ['all'],
    ja: 'ケガをしたら、すぐに担当者に言ってください',
    vi: 'Nếu bị thương, hãy báo ngay cho người phụ trách',
    id_lang: 'Jika terluka, segera beritahu penanggung jawab',
    en: 'If injured, report immediately to your supervisor',
    my: 'ဒဏ်ရာရပါက တာဝန်ခံထံ ချက်ချင်းသတင်းပို့ပါ',
    zh: '受伤时，请立即告知负责人',
  },
  {
    id: 'S04',
    icon: '🦺',
    industries: ['manufacturing', 'construction', 'logistics'],
    ja: '保護具（ヘルメット・手袋・安全靴）を必ずつけてください',
    vi: 'Luôn đeo đồ bảo hộ lao động (mũ bảo hiểm, găng tay, giày an toàn)',
    id_lang: 'Selalu kenakan alat pelindung diri (helm, sarung tangan, sepatu keselamatan)',
    en: 'Always wear protective equipment (helmet, gloves, safety shoes)',
    my: 'ကာကွယ်ရေးပစ္စည်းများ (ဦးထုပ်၊ လက်အိတ်၊ ဘေးကင်းသောဖိနပ်) အမြဲတမ်းဝတ်ဆင်ပါ',
    zh: '必须佩戴防护用品（安全帽、手套、安全鞋）',
  },
  {
    id: 'S05',
    icon: '🏋️',
    industries: ['manufacturing', 'logistics', 'construction'],
    ja: '__weight__kg以上の重いものは__people__人で運んでください',
    vi: 'Vật nặng từ __weight__kg trở lên phải có __people__ người vận chuyển',
    id_lang: 'Benda berat __weight__kg atau lebih harus diangkat oleh __people__ orang',
    en: 'Items weighing __weight__kg or more must be carried by __people__ people',
    my: 'ကီလို __weight__ နှင့်အထက် လေးသောပစ္စည်းများကို လူ __people__ ဦးဖြင့် သယ်ဆောင်ပါ',
    zh: '__weight__kg以上的重物须由__people__人搬运',
    params: [
      { key: 'weight', default: 20, min: 5, max: 100, unit: 'kg' },
      { key: 'people', default: 2, min: 2, max: 5, unit: '人' },
    ],
  },
  {
    id: 'S06',
    icon: '🚜',
    industries: ['manufacturing', 'logistics'],
    ja: 'フォークリフトが通る通路には入ってはいけません',
    vi: 'Không được đi vào đường đi của xe nâng',
    id_lang: 'Jangan masuk ke jalur forklift',
    en: 'Do not enter forklift lanes',
    my: 'ဖော့ကလစ်သွားသောလမ်းကြောင်းသို့ မဝင်ပါနှင့်',
    zh: '禁止进入叉车通行的通道',
  },
  {
    id: 'S07',
    icon: '🙌',
    industries: ['food', 'care'],
    ja: '食品を触る前に必ず手を洗ってください',
    vi: 'Rửa tay trước khi chạm vào thực phẩm',
    id_lang: 'Cuci tangan sebelum menyentuh makanan',
    en: 'Wash hands before handling food',
    my: 'အစားအသောက်ထိမည်ဆိုရင် လက်ကို အရင်ဆေးကြောပါ',
    zh: '接触食品前，请务必洗手',
  },
  {
    id: 'S08',
    icon: '🔪',
    industries: ['food', 'manufacturing'],
    ja: '刃物・カッターは使用後に必ずしまってください',
    vi: 'Sau khi dùng dao, cutter hãy cất ngay vào chỗ',
    id_lang: 'Setelah menggunakan pisau atau cutter, simpan kembali',
    en: 'After using knives or cutters, put them away immediately',
    my: 'ဓားများ၊ ဖြတ်ကြိုးများကို အသုံးပြီးနောက် ချက်ချင်းသိမ်းပါ',
    zh: '刀具、切割机使用后请放回原位',
  },
  {
    id: 'S09',
    icon: '⚠️',
    industries: ['food', 'care', 'retail'],
    ja: '滑りやすい床には注意して歩いてください',
    vi: 'Hãy cẩn thận khi đi trên sàn trơn',
    id_lang: 'Berhati-hatilah saat berjalan di lantai yang licin',
    en: 'Be careful when walking on slippery floors',
    my: 'လျှောတတ်သောကြမ်းပြင်ပေါ်တွင် သတိထားလျှောက်ပါ',
    zh: '请注意在易滑地面上行走',
  },
  {
    id: 'S10',
    icon: '📍',
    industries: ['all'],
    ja: '作業中は指定された場所にいてください',
    vi: 'Trong khi làm việc, hãy ở đúng vị trí quy định',
    id_lang: 'Selama bekerja, tetap di posisi yang ditentukan',
    en: 'During work, stay in your designated area',
    my: 'အလုပ်လုပ်နေစဉ် သတ်မှတ်ထားသောနေရာတွင် နေပါ',
    zh: '作业期间请在指定区域内',
  },
  {
    id: 'S11',
    icon: '🪝',
    industries: ['construction'],
    ja: '高所作業はハーネスを必ず着用してください',
    vi: 'Khi làm việc trên cao, phải đeo dây an toàn',
    id_lang: 'Saat bekerja di ketinggian, selalu gunakan sabuk pengaman',
    en: 'When working at heights, always wear a safety harness',
    my: 'မြင့်သောနေရာတွင် အလုပ်လုပ်သောအခါ ဘေးကင်းရေးကြိုးအမြဲတမ်းဝတ်ဆင်ပါ',
    zh: '高空作业必须佩戴安全绳',
  },
  {
    id: 'S12',
    icon: '⚡',
    industries: ['manufacturing', 'construction'],
    ja: '電気設備には許可なく触れないでください',
    vi: 'Không chạm vào thiết bị điện khi chưa được phép',
    id_lang: 'Jangan menyentuh peralatan listrik tanpa izin',
    en: 'Do not touch electrical equipment without permission',
    my: 'ခွင့်ပြုချက်မရှိဘဲ လျှပ်စစ်ပစ္စည်းများကို မထိပါနှင့်',
    zh: '未经允许不得触碰电气设备',
  },
  {
    id: 'S13',
    icon: '📦',
    industries: ['all'],
    ja: '通路に荷物を置かないでください',
    vi: 'Không để đồ vật trên lối đi',
    id_lang: 'Jangan letakkan barang di jalur pejalan kaki',
    en: 'Do not leave items in walkways',
    my: 'လမ်းကြောင်းပေါ်တွင် ပစ္စည်းများမထားပါနှင့်',
    zh: '禁止在通道内放置货物',
  },
  {
    id: 'S14',
    icon: '🚶',
    industries: ['all'],
    ja: '作業中は走らないでください',
    vi: 'Không chạy trong khi làm việc',
    id_lang: 'Jangan berlari selama bekerja',
    en: 'Do not run during work hours',
    my: 'အလုပ်လုပ်နေစဉ် မပြေးပါနှင့်',
    zh: '作业期间请勿奔跑',
  },
  {
    id: 'S15',
    icon: '☣️',
    industries: ['manufacturing', 'care', 'food'],
    ja: '化学物質の取扱いは手順書に従ってください',
    vi: 'Khi xử lý hóa chất, hãy tuân theo hướng dẫn sử dụng',
    id_lang: 'Ikuti prosedur saat menangani bahan kimia',
    en: 'Follow procedures when handling chemicals',
    my: 'ဓာတုပစ္စည်းများကို ကိုင်တွယ်သောအခါ လုပ်ထုံးလုပ်နည်းကို လိုက်နာပါ',
    zh: '处理化学品时请按操作规程执行',
  },
  {
    id: 'S16',
    icon: '🪜',
    industries: ['construction'],
    ja: '足場を使う前に固定を確認してください',
    vi: 'Kiểm tra giàn giáo đã chắc chắn trước khi sử dụng',
    id_lang: 'Periksa perancah sudah kuat sebelum digunakan',
    en: 'Check that scaffolding is secured before use',
    my: 'ကြံ့ခိုင်မှုကို မအသုံးမပြုမီ စစ်ဆေးပါ',
    zh: '使用脚手架前请确认固定是否牢固',
  },
];

// ─── Emergency Rules (E01–E08) ───────────────────────────────────

export const EMERGENCY_RULES: RuleItem[] = [
  {
    id: 'E01',
    icon: '🩹',
    industries: ['all'],
    ja: 'ケガをした → すぐに担当者に言う',
    vi: 'Bị thương → Báo ngay cho người phụ trách',
    id_lang: 'Terluka → Segera beritahu penanggung jawab',
    en: 'Injured → Report immediately to supervisor',
    my: 'ဒဏ်ရာရပါက → တာဝန်ခံထံ ချက်ချင်းသတင်းပို့ပါ',
    zh: '受伤时 → 立即告知负责人',
  },
  {
    id: 'E02',
    icon: '🔧',
    industries: ['manufacturing'],
    ja: '機械が止まった → 自分で直さない。担当者に言う',
    vi: 'Máy móc bị dừng → Không tự sửa. Báo cho người phụ trách',
    id_lang: 'Mesin berhenti → Jangan diperbaiki sendiri. Beritahu penanggung jawab',
    en: 'Machine stopped → Do not fix yourself. Report to supervisor',
    my: 'စက်ရပ်သွားပါက → မိမိကိုယ်တိုင် မပြင်ပါနှင့်။ တာဝန်ခံထံ သတင်းပို့ပါ',
    zh: '机器停止时 → 不要自行修理，告知负责人',
  },
  {
    id: 'E03',
    icon: '🔥',
    industries: ['all'],
    ja: '火事のとき → 大きな声で「火事だ！」と言う。外に出る',
    vi: 'Khi có hỏa hoạn → Hô to "Cháy!" và ra ngoài ngay',
    id_lang: 'Saat kebakaran → Berteriak "Kebakaran!" dan segera keluar',
    en: 'Fire → Shout "Fire!" loudly and exit immediately',
    my: 'မီးလောင်မှုဖြစ်ပါက → "မီးလောင်တယ်!" ဟု ကျယ်လောင်စွာ အော်ပြီး ချက်ချင်းထွက်ပါ',
    zh: '火灾时 → 大声呼喊着火了！，立即向外疏散',
  },
  {
    id: 'E04',
    icon: '🤒',
    industries: ['all'],
    ja: '体調が悪いとき → 無理せず担当者に言う',
    vi: 'Khi cảm thấy không khỏe → Đừng cố gắng, báo cho người phụ trách',
    id_lang: 'Saat tidak enak badan → Jangan dipaksakan, beritahu penanggung jawab',
    en: 'Feeling unwell → Do not push yourself. Report to supervisor',
    my: 'ကျန်းမာရေးမကောင်းပါက → အတင်းမလုပ်ပါနှင့်။ တာဝန်ခံထံ ပြောပါ',
    zh: '身体不适时 → 不要勉强，告知负责人',
  },
  {
    id: 'E05',
    icon: '🫨',
    industries: ['all'],
    ja: '地震のとき → 頭を守って、机の下や安全な場所に隠れる',
    vi: 'Khi có động đất → Che đầu và ẩn dưới bàn hoặc nơi an toàn',
    id_lang: 'Saat gempa → Lindungi kepala dan berlindung di bawah meja atau tempat aman',
    en: 'Earthquake → Protect your head and shelter under a desk or safe area',
    my: 'ငလျင်လှုပ်သောအခါ → ခေါင်းကို ကာကွယ်ပြီး စားပွဲအောက် သို့မဟုတ် လုံခြုံသောနေရာတွင် ကွယ်ပါ',
    zh: '地震时 → 保护头部，躲到桌下或安全地点',
  },
  {
    id: 'E06',
    icon: '💡',
    industries: ['manufacturing', 'logistics'],
    ja: '停電のとき → その場で動かず、指示を待つ',
    vi: 'Mất điện → Đứng yên tại chỗ, chờ hướng dẫn',
    id_lang: 'Saat mati lampu → Tetap di tempat, tunggu instruksi',
    en: 'Power outage → Stay where you are, wait for instructions',
    my: 'မီးပျက်သောအခါ → နေရာမှ မရွှေ့ပါနှင့်၊ ညွှန်ကြားချက်ကို စောင့်ပါ',
    zh: '停电时 → 不要擅自行动，原地等待指示',
  },
  {
    id: 'E07',
    icon: '☣️',
    industries: ['manufacturing', 'construction'],
    ja: '有害物質に触れた → すぐに水で洗い、担当者に報告',
    vi: 'Tiếp xúc chất độc hại → Rửa ngay bằng nước, báo cho người phụ trách',
    id_lang: 'Terkena bahan berbahaya → Segera cuci dengan air, lapor penanggung jawab',
    en: 'Contact with hazardous material → Wash immediately with water, report to supervisor',
    my: 'အန္တရာယ်ရှိသောပစ္စည်းထိပါက → ရေဖြင့်ချက်ချင်းဆေးကြောပြီး တာဝန်ခံထံ အစီရင်ခံပါ',
    zh: '接触有害物质时 → 立即用清水冲洗，向负责人报告',
  },
  {
    id: 'E08',
    icon: '📢',
    industries: ['construction', 'manufacturing'],
    ja: '同僚がいなくなった → 担当者にすぐに報告',
    vi: 'Đồng nghiệp mất tích → Báo ngay cho người phụ trách',
    id_lang: 'Rekan kerja hilang → Segera lapor penanggung jawab',
    en: 'Colleague missing → Report immediately to supervisor',
    my: 'လုပ်ဖော်ကိုင်ဖက် ပျောက်ဆုံးပါက → တာဝန်ခံထံ ချက်ချင်း သတင်းပို့ပါ',
    zh: '同事失踪 → 立即向负责人报告',
  },
];

// ─── Daily Rules (D01–D12) ───────────────────────────────────────

export const DAILY_RULES: RuleItem[] = [
  {
    id: 'D01',
    icon: '⏰',
    industries: ['all'],
    ja: '始業時間の__minutes__分前に来てください',
    vi: 'Đến nơi làm việc trước __minutes__ phút so với giờ bắt đầu',
    id_lang: 'Datang __minutes__ menit sebelum jam mulai bekerja',
    en: 'Arrive __minutes__ minutes before your start time',
    my: 'အလုပ်စချိန်မတိုင်မီ __minutes__ မိနစ်ကြိုရောက်အောင် လာပါ',
    zh: '请在上班时间前__minutes__分钟到达',
    params: [{ key: 'minutes', default: 15, min: 5, max: 60, unit: '分' }],
  },
  {
    id: 'D02',
    icon: '📞',
    industries: ['all'],
    ja: '休むときは、前日か当日の朝__hour__時までに電話してください',
    vi: 'Nếu nghỉ, hãy gọi điện trước ngày hôm trước hoặc trước __hour__ giờ sáng',
    id_lang: 'Jika tidak masuk, hubungi sehari sebelumnya atau sebelum pukul __hour__ pagi',
    en: 'If absent, call the day before or before __hour__:00 AM that day',
    my: 'မလာနိုင်ပါက တစ်ရက်ကြိုတင် ဖုန်းဆက်ပါ သို့မဟုတ် ထိုနေ့နံနက် __hour__ နာရီမတိုင်မီ ဖုန်းဆက်ပါ',
    zh: '请假时，请在前一天或当天早上__hour__点前打电话联系',
    params: [{ key: 'hour', default: 8, min: 5, max: 12, unit: '時' }],
  },
  {
    id: 'D03',
    icon: '🙋',
    industries: ['all'],
    ja: '困ったことがあれば、すぐに担当者に言ってください',
    vi: 'Khi có khó khăn, hãy báo ngay cho người phụ trách',
    id_lang: 'Jika ada masalah, segera beritahu penanggung jawab',
    en: 'If you have any problem, report it immediately to your supervisor',
    my: 'ဘာပြဿနာမဆို တာဝန်ခံထံ ချက်ချင်းသတင်းပို့ပါ',
    zh: '有困难时，请立即告知负责人',
  },
  {
    id: 'D04',
    icon: '🧹',
    industries: ['all'],
    ja: '作業が終わったら、作業場所をきれいに片付けてください',
    vi: 'Sau khi làm việc xong, hãy dọn dẹp sạch sẽ nơi làm việc',
    id_lang: 'Setelah selesai bekerja, bersihkan tempat kerja',
    en: 'After work, clean up your work area',
    my: 'အလုပ်ပြီးနောက် အလုပ်နေရာကို သန့်ရှင်းစွာ သိမ်းဆည်းပါ',
    zh: '工作结束后，请整理打扫工作区域',
  },
  {
    id: 'D05',
    icon: '📵',
    industries: ['all'],
    ja: 'スマートフォンは休憩時間だけ使ってください',
    vi: 'Chỉ được dùng điện thoại trong giờ nghỉ',
    id_lang: 'Gunakan smartphone hanya saat istirahat',
    en: 'Use smartphones during break time only',
    my: 'စမတ်ဖုန်းကို အနားယူချိန်တွင်သာ သုံးပါ',
    zh: '智能手机仅限休息时间使用',
  },
  {
    id: 'D06',
    icon: '👔',
    industries: ['all'],
    ja: '制服・作業着は毎日清潔なものを着てください',
    vi: 'Hãy mặc đồng phục hoặc quần áo làm việc sạch sẽ mỗi ngày',
    id_lang: 'Kenakan seragam atau pakaian kerja yang bersih setiap hari',
    en: 'Wear clean uniform or work clothes every day',
    my: 'နေ့တိုင်း သန့်ရှင်းသောယူနီဖောင်း သို့မဟုတ် အလုပ်ဝတ်စုံကို ဝတ်ပါ',
    zh: '请每天穿着干净的制服或工作服',
  },
  {
    id: 'D07',
    icon: '📋',
    industries: ['all'],
    ja: '報告・連絡・相談は__supervisor__にしてください',
    vi: 'Báo cáo, liên lạc, trao đổi với __supervisor__',
    id_lang: 'Laporkan, komunikasikan, dan konsultasikan dengan __supervisor__',
    en: 'Report, communicate, and consult with __supervisor__',
    my: 'အစီရင်ခံ၊ ဆက်သွယ်၊ တိုင်ပင်ရေးများကို __supervisor__ ထံ ပြုလုပ်ပါ',
    zh: '汇报、联络、商谈请找__supervisor__',
    usesSupervisorName: true,
  },
  {
    id: 'D08',
    icon: '🗑️',
    industries: ['all'],
    ja: 'ゴミは分別して指定の場所に捨ててください',
    vi: 'Phân loại rác và bỏ vào nơi quy định',
    id_lang: 'Pisahkan sampah dan buang di tempat yang ditentukan',
    en: 'Sort garbage and dispose of it in designated areas',
    my: 'အမှိုက်ကို ခွဲခြားပြီး သတ်မှတ်ထားသောနေရာတွင် စွန့်ပစ်ပါ',
    zh: '请将垃圾分类后丢到指定位置',
  },
  {
    id: 'D09',
    icon: '🤝',
    industries: ['manufacturing', 'construction'],
    ja: '朝礼に必ず参加してください',
    vi: 'Hãy tham gia buổi họp sáng',
    id_lang: 'Harap ikuti rapat pagi setiap hari',
    en: 'Always attend the morning meeting',
    my: 'မနက်အစည်းအဝေးကို မဖြစ်မနေ တက်ရောက်ပါ',
    zh: '请务必参加早会',
  },
  {
    id: 'D10',
    icon: '🔒',
    industries: ['manufacturing', 'food', 'care'],
    ja: 'ロッカーに私物を入れ、作業場に持ち込まないでください',
    vi: 'Cất đồ cá nhân vào tủ khóa, không mang vào nơi làm việc',
    id_lang: 'Simpan barang pribadi di loker, jangan bawa ke area kerja',
    en: 'Store personal items in lockers, do not bring them to the work area',
    my: 'ကိုယ်ပိုင်ပစ္စည်းများကို ဒေါင်ကျတွင်ထားပြီး အလုပ်နေရာသို့ မယူလာပါနှင့်',
    zh: '请将私人物品放入储物柜，不要带入工作区',
  },
  {
    id: 'D11',
    icon: '✅',
    industries: ['manufacturing', 'construction'],
    ja: '作業前に道具・備品を確認してください',
    vi: 'Kiểm tra dụng cụ và vật tư trước khi làm việc',
    id_lang: 'Periksa peralatan dan perlengkapan sebelum bekerja',
    en: 'Check tools and supplies before starting work',
    my: 'အလုပ်မစမီ ကိရိယာများနှင့် ပစ္စည်းများကို စစ်ဆေးပါ',
    zh: '工作前请确认工具和设备',
  },
  {
    id: 'D12',
    icon: '🕐',
    industries: ['all'],
    ja: '退勤時にタイムカードを押してください',
    vi: 'Bấm thẻ chấm công khi tan ca',
    id_lang: 'Absen pulang saat selesai bekerja',
    en: 'Punch your time card when leaving',
    my: 'အလုပ်ထွက်သောအခါ အချိန်ကတ်ကို နှိပ်ပါ',
    zh: '下班时请打卡',
  },
];

// ─── Phrases (P01–P12) ──────────────────────────────────────────

export const PHRASES: RuleItem[] = [
  {
    id: 'P01',
    industries: ['all'],
    ja: '終わりました',
    vi: 'Tôi đã xong việc rồi',
    id_lang: 'Sudah selesai',
    en: 'I have finished',
    my: 'ပြီးပါပြီ',
    zh: '做完了',
    jaRuby: '<ruby>終<rt>お</rt></ruby>わりました',
    context: {
      ja: '作業や指示された仕事が完了したときに使う',
      vi: 'Dùng khi hoàn thành công việc được giao',
      id: 'Digunakan saat pekerjaan yang diberikan selesai',
      en: 'Use when you have completed your assigned task',
      my: 'တာဝန်ပေးသောအလုပ်ပြီးဆုံးသောအခါ သုံးသည်',
      zh: '完成被分配的工作或任务时使用',
    },
  },
  {
    id: 'P02',
    industries: ['all'],
    ja: '確認してください',
    vi: 'Xin hãy kiểm tra',
    id_lang: 'Tolong diperiksa',
    en: 'Please check this',
    my: 'စစ်ဆေးပေးပါ',
    zh: '请确认',
    jaRuby: '<ruby>確認<rt>かくにん</rt></ruby>してください',
    context: {
      ja: '作業内容や判断に迷ったとき、上司に確認を依頼するときに使う',
      vi: 'Dùng khi không chắc về công việc hoặc cần xác nhận từ cấp trên',
      id: 'Digunakan saat ragu tentang pekerjaan atau perlu konfirmasi atasan',
      en: 'Use when unsure about a task or need supervisor confirmation',
      my: 'အလုပ်အကြောင်း မသေချာသောအခါ သို့မဟုတ် အကြီးအကဲထံ အတည်ပြုရန် သုံးသည်',
      zh: '对工作内容或判断有疑问，请求上级确认时使用',
    },
  },
  {
    id: 'P03',
    industries: ['all'],
    ja: '困っています',
    vi: 'Tôi đang gặp khó khăn',
    id_lang: 'Saya sedang kesulitan',
    en: 'I am having trouble',
    my: 'အခက်တွေ့နေပါသည်',
    zh: '遇到困难了',
    jaRuby: '<ruby>困<rt>こま</rt></ruby>っています',
    context: {
      ja: '仕事で問題が起きたときや、どうすればよいか分からないときに使う',
      vi: 'Dùng khi gặp vấn đề hoặc không biết phải làm gì',
      id: 'Digunakan saat ada masalah atau tidak tahu harus berbuat apa',
      en: 'Use when facing a problem or unsure what to do',
      my: 'ပြဿနာတစ်ခုကြုံသောအခါ သို့မဟုတ် ဘာလုပ်ရမည်မသိသောအခါ သုံးသည်',
      zh: '工作中遇到问题或不知该怎么办时使用',
    },
  },
  {
    id: 'P04',
    industries: ['all'],
    ja: 'わかりません',
    vi: 'Tôi không hiểu',
    id_lang: 'Saya tidak mengerti',
    en: 'I do not understand',
    my: 'နားမလည်ပါ',
    zh: '不明白',
    jaRuby: 'わかりません',
    context: {
      ja: '指示の意味が分からないときに使う。遠慮せず言ってよい',
      vi: 'Dùng khi không hiểu hướng dẫn. Không cần ngại ngùng',
      id: 'Digunakan saat tidak mengerti instruksi. Jangan ragu mengatakannya',
      en: 'Use when you do not understand instructions. Do not hesitate to say this',
      my: 'ညွှန်ကြားချက်နားမလည်သောအခါ သုံးသည်။ တုံ့ဆိုင်းခြင်းမရှိဘဲ ပြောနိုင်သည်',
      zh: '不明白指示内容时使用。不用客气，可以直接说',
    },
  },
  {
    id: 'P05',
    industries: ['all'],
    ja: 'もう一度 言ってください',
    vi: 'Xin hãy nói lại một lần nữa',
    id_lang: 'Tolong ulangi sekali lagi',
    en: 'Please say that again',
    my: 'နောက်တစ်ခါ ပြောပြပါ',
    zh: '请再说一遍',
    jaRuby: 'もう<ruby>一度<rt>いちど</rt></ruby> <ruby>言<rt>い</rt></ruby>ってください',
    context: {
      ja: '聞き取れなかったときや、もう一度確認したいときに使う',
      vi: 'Dùng khi không nghe rõ hoặc muốn xác nhận lại',
      id: 'Digunakan saat tidak mendengar jelas atau ingin mengkonfirmasi ulang',
      en: 'Use when you could not hear clearly or want to confirm again',
      my: 'ကြားရမှားသောအခါ သို့မဟုတ် ထပ်မံအတည်ပြုလိုသောအခါ သုံးသည်',
      zh: '没听清楚或想再确认一次时使用',
    },
  },
  {
    id: 'P06',
    industries: ['all'],
    ja: 'トイレに行ってもいいですか',
    vi: 'Tôi có thể đi vệ sinh được không?',
    id_lang: 'Boleh saya ke toilet?',
    en: 'May I go to the restroom?',
    my: 'အိမ်သာ သွားလို့ ရမလား',
    zh: '可以去洗手间吗？',
    jaRuby: 'トイレに<ruby>行<rt>い</rt></ruby>ってもいいですか',
    context: {
      ja: '作業中にトイレに行く許可を求めるときに使う',
      vi: 'Dùng khi cần xin phép đi vệ sinh trong giờ làm việc',
      id: 'Digunakan saat meminta izin ke toilet saat bekerja',
      en: 'Use when asking permission to use the restroom during work',
      my: 'အလုပ်ချိန်အတွင်း အိမ်သာသွားခွင့်တောင်းသောအခါ သုံးသည်',
      zh: '工作中需要去洗手间请求许可时使用',
    },
  },
  {
    id: 'P07',
    industries: ['all'],
    ja: '休憩はいつですか',
    vi: 'Khi nào được nghỉ giải lao?',
    id_lang: 'Kapan waktu istirahat?',
    en: 'When is break time?',
    my: 'အနားယူချိန် ဘယ်အချိန်လဲ',
    zh: '什么时候休息？',
    jaRuby: '<ruby>休憩<rt>きゅうけい</rt></ruby>はいつですか',
    context: {
      ja: '休憩の時間や場所を確認するときに使う',
      vi: 'Dùng để hỏi giờ và nơi nghỉ giải lao',
      id: 'Digunakan untuk menanyakan waktu dan tempat istirahat',
      en: 'Use to ask about break time and location',
      my: 'အနားချိန်နှင့် နေရာကို မေးသောအခါ သုံးသည်',
      zh: '确认休息时间和地点时使用',
    },
  },
  {
    id: 'P08',
    industries: ['manufacturing', 'construction', 'logistics'],
    ja: '道具が足りません',
    vi: 'Thiếu dụng cụ',
    id_lang: 'Alat tidak cukup',
    en: 'I need more tools',
    my: 'ကိရိယာ မလုံလောက်ပါ',
    zh: '工具不够',
    jaRuby: '<ruby>道具<rt>どうぐ</rt></ruby>が<ruby>足<rt>た</rt></ruby>りません',
    context: {
      ja: '作業に必要な道具が不足しているときに担当者に伝えるために使う',
      vi: 'Dùng để báo với người phụ trách khi thiếu dụng cụ làm việc',
      id: 'Digunakan untuk memberitahu penanggung jawab saat kekurangan alat',
      en: 'Use to inform the supervisor when work tools are insufficient',
      my: 'လုပ်ငန်းကိရိယာမလုံလောက်သောအခါ တာဝန်ခံထံ အကြောင်းကြားရန် သုံးသည်',
      zh: '工作所需工具不足时，向负责人汇报时使用',
    },
  },
  {
    id: 'P09',
    industries: ['manufacturing', 'construction', 'food'],
    ja: '材料がありません',
    vi: 'Hết nguyên liệu',
    id_lang: 'Bahan habis',
    en: 'Materials have run out',
    my: 'ပစ္စည်းကုန်သွားပါပြီ',
    zh: '没有材料了',
    jaRuby: '<ruby>材料<rt>ざいりょう</rt></ruby>がありません',
    context: {
      ja: '作業に必要な材料や部品がなくなったときに使う',
      vi: 'Dùng khi nguyên liệu hoặc linh kiện cần thiết đã hết',
      id: 'Digunakan saat bahan atau komponen yang diperlukan habis',
      en: 'Use when necessary materials or parts have run out',
      my: 'လိုအပ်သောပစ္စည်းများ ကုန်ဆုံးသောအခါ သုံးသည်',
      zh: '工作所需材料或零件用完时使用',
    },
  },
  {
    id: 'P10',
    industries: ['all'],
    ja: '手伝ってください',
    vi: 'Xin hãy giúp tôi',
    id_lang: 'Tolong bantu saya',
    en: 'Please help me',
    my: 'ကူညီပေးပါ',
    zh: '请帮帮我',
    jaRuby: '<ruby>手伝<rt>てつだ</rt></ruby>ってください',
    context: {
      ja: '一人では対応できない作業があるときに使う',
      vi: 'Dùng khi có công việc không thể tự mình xử lý một mình',
      id: 'Digunakan saat ada pekerjaan yang tidak bisa ditangani sendiri',
      en: 'Use when there is work that cannot be handled alone',
      my: 'တစ်ယောက်တည်း မကိုင်တွယ်နိုင်သောအလုပ်ရှိသောအခါ သုံးသည်',
      zh: '有无法独自完成的工作时使用',
    },
  },
  {
    id: 'P11',
    industries: ['all'],
    ja: '遅刻します、すみません',
    vi: 'Tôi sẽ đến muộn, xin lỗi',
    id_lang: 'Saya akan terlambat, maaf',
    en: 'I will be late, sorry',
    my: 'နောက်ကျပါမယ်၊ တောင်းပန်ပါတယ်',
    zh: '我会迟到，对不起',
    jaRuby: '<ruby>遅刻<rt>ちこく</rt></ruby>します、すみません',
    context: {
      ja: '出勤前に遅れることが分かったとき、必ず電話で連絡する',
      vi: 'Khi biết sẽ đến muộn, nhất thiết phải gọi điện báo trước',
      id: 'Saat tahu akan terlambat, wajib menghubungi lewat telepon terlebih dahulu',
      en: 'When you know you will be late, always call in advance to inform',
      my: 'နောက်ကျမည်သိသောအခါ ဖုန်းဆက်၍ အကြောင်းကြားရမည်',
      zh: '上班前知道会迟到时，务必打电话联系',
    },
  },
  {
    id: 'P12',
    industries: ['all'],
    ja: 'ありがとうございます',
    vi: 'Cảm ơn bạn',
    id_lang: 'Terima kasih',
    en: 'Thank you',
    my: 'ကျေးဇူးတင်ပါသည်',
    zh: '谢谢',
    jaRuby: 'ありがとうございます',
    context: {
      ja: '助けてもらったときや指示を受けたときに使う。積極的に使おう',
      vi: 'Dùng khi được giúp đỡ hoặc nhận hướng dẫn. Hãy chủ động sử dụng',
      id: 'Digunakan saat dibantu atau menerima instruksi. Gunakan secara aktif',
      en: 'Use when receiving help or instructions. Use it proactively',
      my: 'အကူအညီရသောအခါ သို့မဟုတ် ညွှန်ကြားချက်ရသောအခါ သုံးသည်။ တက်တက်ကြွကြွ သုံးပါ',
      zh: '接受帮助或接受指示时使用。请积极使用',
    },
  },
];
